#!/bin/bash

### author: p.budrewicz

. $( dirname $0 )/user.key 
. $( dirname $0 )/colors.env
 
VERBOSE=0
SHOW_RESPONSES=0 # show curl responses
DRY=0 # do not run curl
DRY_SCHEMA="xy" # default schema when faking bridge interactions
LIGHTS="" # light list 
SLEEP=0.7 # sleeping time for blinking etc.
STEPS="10" # number of steps in transitions
EXP="0" # linear (not exponential) brightness
PERSIST=0 # shall we continue even if lights were turned off
OFF=0 # shall we turn the lights off in the end of action

CRAWL=0.05
CRAWLB=10

# bulb gamut parameters
RED_CORNER="0.6915 0.3083"
GREEN_CORNER="0.17 0.7"
BLUE_CORNER="0.1532 0.0475"

FAKE_bri=111
FAKE_ct="ct 200 111"
FAKE_xy="xy $RED_CORNER 111"
FAKE_hue="hue 45000 150 111"
FAKE_t="t 2800 111"

# sunrise color arch and brightnes sequence
SUNRISE="0.68 0.3 1
0.62 0.37 1
0.57 0.4  3
0.52 0.41 5
0.5 0.41  9
0.48 0.41 15
0.43 0.40 27
0.4 0.38  48
0.37 0.35 83 
0.32 0.33 145
0.31 0.32 254"

LINEAR_SUNRISE="0.68 0.3 1
0.62 0.37 26
0.57 0.4  51
0.52 0.41 76
0.5 0.41  102
0.48 0.41 127
0.43 0.40 152
0.4 0.38  178
0.37 0.35 203
0.32 0.33 228
0.31 0.32 254"

# TODO: add support to setting color of celsius temperature and remove it from weather.sh
# TODO: conversion ct -> xy and maybe xy -> ct.

TEMP=$( getopt -o b:d::ehk:l:op:Prs:v:: --long bridge:,dry::,exp,help,key:,light:,off,period:,persist,responses,steps:,verbose:: -n $0 -- "$@" )

if [ $? != 0 ] ; then echo "Cannot parse options. Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

dump_data () {
    echo VERBOSE=$VERBOSE
    echo SHOW_RESPONSES=$SHOW_RESPONSES
    echo DRY=$DRY
    echo LIGHTS=$LIGHTS
    echo SLEEP=$SLEEP
    echo STEPS=$STEPS
    echo EXP=$EXP
    echo PERSIST=$PERSIST
    echo CRAWL=$CRAWL
    echo CRAWLB=$CRAWLB
}

scan_net () {
    #     feedback -n .
    gssdp-discover -n 5 | grep Location: | while  read loc url ; do
	if curl -s $url | grep -qi "Philips hue bridge" ; then
	    echo $url |sed s/description.xml//
	    return 0;
	fi 
    done
    return 1
}

discover_bridge () {
    bridge_url=$(scan_net)
    echo bridge_url=$bridge_url
}

unjson () {
    perl -MJSON -e '$s = decode_json(<STDIN>); eval "print \$s->'$1'";'
}

feedback () {
    if [ "$VERBOSE" -gt "0" ] ; then
        echo "$@" 1>&2
    fi
}

polite_curl () {
    if  [ "$VERBOSE" -gt "1" ] || [ "$SHOW_RESPONSES" = "1" ]; then
        feedback "running curl $@"
    fi
    if [ "$DRY" = "1" ] ; then
        return
    fi
    if [ "$SHOW_RESPONSES" = "1" ]; then
        curl "$@"
    else
        curl "$@" >/dev/null 2>/dev/null
    fi
}

### some fun math...

interpolate () { # this function takes 
    # step_count (xy|hue|ct|bri) L1 L2 [L3] R1 R2 [R3] current_step ->  I1 I2 [I3] # interpolated values    

    #  feedback interpolating $@

  debug "$@"
  STEPS=$1
  SCHEMA=$2
  
  case $SCHEMA in 
      xy|hue)
          FROM1=$3
          FROM2=$4
          FROMB=$5
          TO1=$6
          TO2=$7
          TOB=$8
	  STEP=$9
          ;;
      ct|[Tt])
          FROM1=$3
          FROMB=$4
          TO1=$5
          TOB=$6
	  STEP=$7
          ;;
      pair)
          FROM1=$3
          FROM2=$4
          TO1=$5
          TO2=$6
          STEP=$7
          ;;
      bri)
          FROMB=$3
          TOB=$4
          STEP=$5
          ;;
  esac
  debug F1:$FROM1 T1:$TO1 STEPS:$STEPS STEP:$STEP
  if [ "$SCHEMA" != "pair" ] ; then
      if [ "$EXP" = "1" ] ; then
          BRI=$( calc %d "((($TOB / $FROMB) ** (1.0/$STEPS)) ** $STEP ) * $FROMB" )
      else
          BRI=$( calc %d "($TOB - $FROMB)/$STEPS * $STEP + $FROMB" ) 
      fi
      debug b:$BRI
  fi
  case $SCHEMA in 
      xy)
	  VAL1=$( calc "($TO1 - $FROM1)/$STEPS * $STEP + $FROM1" )
	  VAL2=$( calc "($TO2 - $FROM2)/$STEPS * $STEP + $FROM2" )
          debug x:$VAL1 y:$VAL2
          echo $SCHEMA $VAL1 $VAL2 $BRI
          ;;
      hue)
	  VAL1=$( calc %d "($TO1 - $FROM1)/$STEPS * $STEP + $FROM1" )
	  VAL2=$( calc %d "($TO2 - $FROM2)/$STEPS * $STEP + $FROM2" ) 
          debug hue:$VAL sat:$VAL2
          echo $SCHEMA $VAL1 $VAL2 $BRI
          ;;
      ct)
	  VAL1=$( calc %d "($TO1 - $FROM1)/$STEPS * $STEP + $FROM1" )
	  debug mirek:$VAL1
          echo $SCHEMA $VAL1 $BRI
          ;;
      [tT])
	  VAL1=$( calc %d "((($TO1 / $FROM1) ** (1.0/$STEPS)) ** $STEP ) * $FROM1" )
	  debug temp:$VAL1
	  echo t $VAL1  $BRI
	  ;;
      pair)
	  VAL1=$( calc "($TO1 - $FROM1)/$STEPS * $STEP + $FROM1" )
	  VAL2=$( calc "($TO2 - $FROM2)/$STEPS * $STEP + $FROM2" )          
          echo $VAL1  $VAL2
          ;;
      bri)
          echo $BRI
          ;;
  esac
}

debug () {
  :  echo "$@" >&2
}

calc () { # use perl for floating point calculations
    case $1 in
	%f|%d)
	    fmt=$1
	    shift
	    ;;
	*)
	    fmt="%f"
	    ;;
    esac
    echo -n $( echo "printf (\"$fmt\", $@)" | perl )
}

K_2_xy () {
    
    if [[ "$1" =~ T([0-9]+) ]] ; then
        T="${BASH_REMATCH[1]}"
    else
        T=4500
    fi

    if [[ $T -lt 1000 ]] ; then
        T=1000
        LOW=1000
        HIGH=1500
    fi
    if [[ $T -gt 20000 ]] ; then
        T=20000
        LOW=10000
        HIGH=20000
    elif [[ $T -gt 10000 ]] ; then
        LOW=10000
        HIGH=20000
    elif [[ $T -gt 7000 ]] ; then
        LOW=7000
        HIGH=10000
    else
        LOW=$( calc %d "int($T / 500) * 500" )
        HIGH=$( calc %d "(1 + int($T / 500)) * 500" )
    fi
    
    HIGH_COLOR=$( export T$HIGH ; sh -c "echo \$T$HIGH" ) # the trick is to show value of variable with calculated name, as  ${T$T} does not work
    LOW_COLOR=$( export T$LOW ; sh -c "echo \$T$LOW" )

    echo $( interpolate $(( $HIGH - $LOW )) pair $LOW_COLOR $HIGH_COLOR $(( $T - $LOW )) )
    
}

ct_2_xy () {
    echo $( K_2_xy T$( calc "1000000 / $1" ) )
}

### end math
maybe_give_up () {
    if [ "$PERSIST" = "1" ] ; then return 0 ; fi

    if ! is_light_on $light ; then
        feedback User turned the light $light off - giving up
        set_color hue 45000 200 254
        set_light off         
        exit 0
    fi
}

maybe_off () {
    if [ "$OFF" = "1" ] ; then
	set_light off
    fi
}

maybe_help_needed () {
    for word ; do
        #        echo debug $word
        if [ "$word" = "help" ] ; then
            show_help 0
        fi
    done
}
    
for_lights () {
    for word ; do
        #        echo debug $word
        if [ "$word" = "help" ] ; then
            "$@"
            exit 0
        fi
    done
    mandatory_lights
    for light in $LIGHTS ; do
        "$@" &
    done
    wait
}

alert () { 
    HELPTEXT="
$0 alert - blink mode on
"
    maybe_help_needed "$@"
    mandatory_lights
    set_light on 
    feedback alert on light $light
    polite_curl -s -X PUT -d '{"alert":"select"}' http://$bridge_ip/api/$user_key/lights/$light/state 
}

time_2_sec () {
    # calculate how many seconds is in 3:00m
    :    
}

first ()
{
    echo $1
}

transit_to_color () {
    # gently change current color into new one
    # TODO: move to "until/for" time schema like in fade

    HELPTEXT="
hue transit {to_color} {to_brightness} - must be in currently used schema
    transit from {from_color} {from_brightness} {to_color} {to_brightness} 
             - color schema should be the same or you can transit from ct to xy.

    for help on describing color run '$(basename $0) color help'
"
    maybe_help_needed "$@"
    mandatory_lights
    if [ "$1" = "from" ] ; then 
        shift
        schema=$1 
        case $schema in
            xy|hue)                                
                if [ "$4" = "" ] ; then
                    show_help 1 too few parameters: two numbers expected $*
                fi
                set_bulb_color $light $schema $2 $3 $4
                shift 4
                ;;
            ct)
                if [ "$3" = "" ] ; then
                    show_help 1 too few parameters: mirek expected $*
                fi
                set_bulb_color $light $schema $2 $3
                shift 3
                ;;
            [tT])
                if [ "$2" = "" ] ; then
                    show_help 1 too few parameters: tempearature expected $*
                fi
                schema=T
		COLOR=T$2
		SAVED_TEMP=$2
                set_bulb_color $light $COLOR $3 
                shift 3
                ;;
            *)
                COLOR=$( describe_color $schema )
                if [ "$2" = "" ] ; then
                    show_help 1 too few parameters $*
                fi
                schema=xy
                set_bulb_color $light xy $COLOR $2
                shift 2
                ;;
        esac
    fi
    
    schema=$1

    if [ "$schema" = "" ] ; then
	show_help 1 no target color description
    fi
    SAVED_COLOR=$( get_color $light )
    SAVED_SCHEMA=$( first $SAVED_COLOR )
    SAVED_BRIGHTNESS=$( get_brightness $light )
    TRANSIT="$SAVED_SCHEMA-$schema"
    case "$TRANSIT" in
	xy-xy|ct-ct|hue-hue|[tT]-[tT])
	    :
	    ;;
	[tT]-xy|xy-[tT])
	     show_help 1 'Cannot transit to T schema from current color - use "transit from"'
	    ;;
	ct-xy)
	    SAVED_COLOR="$( ct_2_xy $( first $SAVED_COLOR ) )"
	    ;;
	*)
	    :	    show_help 1 Cannot transit from $SAVED_SCHEMA to $schema
	    ;;
    esac
    feedback transit from $SAVED_COLOR to "$@" in $STEPS steps
    for i in $( seq 1 $STEPS ) ; do
        case $1 in # hands off 
            xy|hue)                                
                if [ "$4" = "" ] ; then
                    show_help 1 too few parameters specified $*
                fi
                NEW_COLOR=$( interpolate $STEPS $SAVED_COLOR $2 $3 $4 $i) ;;            
            ct)
                if [ "$3" = "" ] ; then
                    show_help 1 too few parameters specified $*
                fi
                NEW_COLOR=$( interpolate $STEPS $SAVED_COLOR $2 $3  $i) ;;
            [tT])      
                if [ "$3" = "" ] ; then
                    show_help 1 too few parameters specified $*
                fi
                schema=t
                NEW_COLOR=$( interpolate $STEPS T $SAVED_TEMP $SAVED_BRIGHTNESS $2 $3 $i) 
                ;;
            *)      
                if [ "$2" = "" ] ; then
                    show_help 1 too few parameters specified $*
                fi
                COLOR=$( describe_color $1 )
                schema=xy
                NEW_COLOR=$( interpolate $STEPS $SAVED_COLOR $COLOR $2 $i) ;;           
        esac
#         if [ "$schema" != "$SAVED_SCHEMA" ] ; then
#             # TODO: transfer  ct -> xy
#             echo "Cannot transit from $SAVED_SCHEMA to $schema"
#             exit 1
#         fi
        set_bulb_color $light $NEW_COLOR 
        sleep $SLEEP
        maybe_give_up $light
    done
    maybe_off
}

hue_pulse () {
    HELPTEXT="
$0 pulse COLOR - switch to COLOR for a moment 
" 
    maybe_help_needed "$@"
    mandatory_lights
    SAVED_COLOR=$( get_color $light )
    set_bulb_color $light "$@"
    sleep $SLEEP;  
    set_bulb_color $light $SAVED_COLOR
}

clone_light () {
HELPTEXT="
hue clone LIGHT - set light as current LIGHT
"
    if [ "$1" = "" ] ; then
        show_help 1 no light number
    fi
    maybe_help_needed $*
    mandatory_lights
    set_color $(get_color $1)
}

blink () {

    HELPTEXT="
hue blink 
       until TIME   - blink until specified time
       for SECONDS  - for that many SECONDS
       once         - once
       times NUMBER - NUMBER times
    differrent TIME formats accepted:
      - 17:32
      - tomorrow 9:00
      - Tuesday
      
"
    maybe_help_needed "$@"
    mandatory_lights
    cmd=$1
    shift
    # $light set outside
    case $cmd in
	[u]ntil) # until is a keyword and breaks emacs's and vim's formatting. LOL
	    if [ "$1" = "" ] ; then
		show_help 1 no time specified
	    fi
            TIME="$1"
	    UNTIL=$( date --date "$TIME" +%s)
	    feedback "Blinking until $TIME ($(( $UNTIL - $( date +%s ) ))s)"
	    ;;
	[f]or) # for is a keyword and breaks emacs's and vim's formatting. LOL
	    if [ "$1" = "" ] ; then
		show_help 1 no period specified
	    fi
	    feedback blinking for $1 seconds
	    UNTIL=$(( $( date +%s ) + $1))
	    ;;
	once)
	    feedback blinking once
	    alert $light
	    exit 0
	    ;;
	times)
	    if [ "$1" = "" ] ; then
		show_help 1 number of times not specified
	    fi
	    feedback blinking $1 times
	    for i in $(seq 1 $1) ; do
		alert ; sleep $SLEEP
                maybe_give_up $light
	    done
	    exit 0
	    ;;
	*)
	    show_help 1 unknown subcommand $cmd
	    ;;
    esac
		
    mandatory_lights
    set_light on
    sleep 1 # wait 4 reaction

    while [ $( date +%s )  -lt $UNTIL ] ; do        
        alert $light
        sleep $SLEEP
        maybe_give_up $light 
    done

}


color_loop () { 

    effect=colorloop
    if [ "$1" = "off" ] ; then
        effect=none
        shift
    fi

    if [ "$1" = "" ] ; then
        echo "$0 [off] light_list"
        exit 0
    fi

    for light; do
        polite_curl -s -X PUT -d '{"effect":"'$effect'"}' http://$bridge_ip/api/$user_key/lights/$light/state 
    done
}

random () {
    if [ "$1" = "" ] ; then
	RANGE=1
    else
	RANGE=$1
    fi
    calc "$RANDOM / 32767 * $RANGE"
}

adjust_color () {

    SCHEMA=$1
    BX=$2; BY=$3; BB=$4
    DX=$5; DY=$6; DB=$7
    
    echo $SCHEMA $( calc $BX + $DX ) $( calc $BY + $DY ) $( calc %d $BB + $DB )
}

chase () {
#TODO: make it working and actually chasing each other more than once
    HELPTEXT=" 
  make all specified lights exchange their colors in circle
  (unsupported yet) 
"
    maybe_help_needed "$@"
    mandatory_lights
  
    while [ "$1" != "$light" ] ; do 
        shift
    done
    target=$2  
    
    feedback "Chasing $light -> $target"
    crawl $target  

}

crawl () {

#TODO: Implement crawiling for other schemas
    HELPTEXT="
hue crawl [x [y [b]] ] -- crawl color in CIE space in x and y range 
                     default y = x; x = 0.05; b=10
"
    maybe_help_needed "$@"
    mandatory_lights

    if [ "$1" != "" ] ; then
        target=$1
    else
        target=$light
    fi

    BASE_COLOR=$( get_color $target )
    for i in $(seq 1 10 ) ; do
        R=$( random 6.283 )
	# DX=$( calc $( random $CRAWL ) - $CRAWL / 2 ) # uniform on |x,y| disc
	# DY=$( calc $( random $CRAWL ) - $CRAWL / 2 ) #
        DX=$( calc "$CRAWL * sin( $R ) " )           # uniform on a circle 
        DY=$( calc "$CRAWL * cos( $R ) " )           #
	DB=$( calc $( random $CRAWLB ) - $CRAWLB / 2 )
	transit_to_color $( adjust_color $BASE_COLOR $DX $DY $DB ) 
	sleep $SLEEP
    done
    transit_to_color $BASE_COLOR
    
}


fade () { 

    HELPTEXT="
hue fade 
     until TIME
     for PERIOD
"    
    maybe_help_needed "$@"
    mandatory_lights
    #TODO: ideas: do not force whole fade out when off - fade from current - sunset fade? 
    cmd=$1 ; shift
    TIME="$*" 
    if [ "$TIME" = "" ] ; then
    	show_help 1
    fi
    COLOR=$( get_color $light )
    SCHEMA=$( first $COLOR )
    
    b=$(  get_brightness $light)

    case $cmd in 
        [u]ntil) # until is a keyword and breaks emacs's and vim's formatting. LOL
            feedback "fading until $TIME"
            END_TIME=$( date --date "$TIME" +%s)
            ;;
        [f]or) # for is a keyword and breaks emacs's and vim's formatting. LOL
            END_TIME=$(( $( date +%s ) + $TIME ))
            feedback "fading for $TIME seconds"
            ;;
        *)
            show_help 1
            ;;
    esac
    
    while [ "$b" -gt "0" ] ; do # we adapt on every loop iteration
        SECONDS=$(( $END_TIME - $( date +%s ) ))
        if [ "$b" -gt "$SECONDS" ] ; then
            ASLEEP=1 
            newb=$( calc "%d"  "$b / $SECONDS * ($SECONDS - 1)" )
        else
            ASLEEP=$( calc %d "$SECONDS / $b" )
            newb=$(( $b - 1 ))            
        fi
        feedback "waiting $ASLEEP seconds ($SECONDS seconds left)"
	sleep $ASLEEP
        maybe_give_up
    	set_brightness $newb 
        if [ "$PERSIST" = "0" ] ; then
	    b=$( get_brightness $light) # we accept external changes... 
        fi
    done 
    set_light off $light    
}

get_color () { # one light only - passed as parameter
    
    if [ "$1" = "" ] ; then
        show_help 1 LIGHT number not provided
    fi

    if [ "$DRY" = "1" ] ; then
        case $DRY_SCHEMA in 
            xy)
                feedback Faking light $1 is $FAKE_xy.
                echo $FAKE_xy
                ;;
            ct)
                feedback Faking light $1 is $FAKE_ct.
                echo $FAKE_ct
                ;;
            hue)
                feedback Faking light $1 is $FAKE_hue.
                echo $FAKE_hue 
                ;;
            [tT])
                feedback Faking light $1 is $FAKE_t
                echo $FAKE_t 
                ;;
            *)
                show_help 1 bad schema for dry run: $DRY_SCHEMA
                ;;
        esac
        return 
    fi
    L=$( get_lights_json $1 )
    color_type=$( echo "$L" | unjson '{state}{colormode}' )
    on=$( echo "$L" | unjson '{state}{on}' )
    case $color_type in
	xy)
	    x=$( echo $L | unjson '{state}{xy}[0]' )
	    y=$( echo $L | unjson '{state}{xy}[1]' )
	    bri=$( echo $L | unjson '{state}{bri}' )
	    echo xy $x $y $bri  $( if ! is_light_on $1; then echo "# off" ; fi )
	    ;;
	hs)
	    hue=$( echo $L | unjson '{state}{hue}' )
	    sat=$( echo $L | unjson '{state}{sat}' )
	    bri=$( echo $L | unjson '{state}{bri}' )
	    echo hue $hue $sat $bri 
	    ;;
	ct)
	    ct=$( echo $L | unjson '{state}{ct}' )
	    bri=$( echo $L | unjson '{state}{bri}' )
	    echo ct $ct $bri
            ;;
        *)
            show_help 1 bad color schema $color_type
            ;;
    esac
}

get_brightness () { 
    if [ "$DRY" = "1" ] ; then
        echo $FAKE_bri
        return
    fi
    echo $( get_lights_json $1 | unjson '{state}{bri}' )
}


get_config_json () { 
    curl -s -X GET  http://$bridge_ip/api/$user_key/config
}


get_lights_json () { 

    if [ "$1" != "" ] ; then
        curl -s -X GET  http://$bridge_ip/api/$user_key/lights/$1
    else
        curl -s -X GET  http://$bridge_ip/api/$user_key/lights
    fi
    
}


get_on_off () { 
    get_lights_json $1 |unjson '{state}{on}'
}


is_light_on () {

    if [ "$DRY" = "1" ] ; then
        feedback Fake light $1 is on
        return 0
    fi

    if [ "$(get_on_off $1)" = "1" ] ; then
        return 0
    else
        return 1
    fi
}


set_light () { 

    HELPTEXT="
hue light on|off
"
    maybe_help_needed "$@"
    if [ "$1" = "" ] ; then
        show_help 1 light status not specified
    fi
    mandatory_lights

    ONOFF=$1
    case  $ONOFF in
        on)
            mandatory_lights
            feedback setting light $light on
            polite_curl -s -X PUT -d '{"on":true}' http://$bridge_ip/api/$user_key/lights/$light/state 
            ;;
        off)
            mandatory_lights
            feedback setting light $light off
            polite_curl -s -X PUT -d '{"on":false}' http://$bridge_ip/api/$user_key/lights/$light/state 
            ;;
        *)
            show_help 1 bad light status $ONOFF 
    esac
    
}

my_loop () { 
    hue=0
    #TODO 
    while true ; do
        ./set_color.sh $1 hue $hue 254 100
        hue=$(( ( $hue + 10000 ) % 65535 ))
        sleep $SLEEP
    done
}


set_brightness () { 

    HELPTEXT="
hue set brightness {brightness:1-254} - setting brightnes
"
    maybe_help_needed "$@"
    if [ "$1" = "" ] ; then
        show_help 1 no brightness value specified
    fi
    case $1 in
	max) BRIGHTNESS=254 ;;
	min) BRIGHTNESS=1 ;;
	*)  BRIGHTNESS=$1 ;;
    esac
    mandatory_lights
    feedback setting brightness of light $light to $BRIGHTNESS    
    FAKE_bri=$BRIGHTNESS
    polite_curl -s -X PUT -d '{"bri":'$BRIGHTNESS'}' http://$bridge_ip/api/$user_key/lights/$light/state 
}

set_hue () {
    HELPTEXT="
hue [set] color hue {hue:0-65535} {saturation:1-254} {brightness:1-254}
   
"
    maybe_help_needed "$@"
    mandatory_lights
    if [ "$3" = "" ] ; then
        show_help 1 $*
    else
	case $3 in
	    max) BRIGHTNESS=254 ;;
	    min) BRIGHTNESS=1 ;;
	    *)  BRIGHTNESS=$3 ;;
	esac
    fi    
    feedback setting hue to "$@"
    polite_curl -s -X PUT -d '{"on":true, "hue":'$1', "sat":'$2',"bri":'$BRIGHTNESS'}' http://$bridge_ip/api/$user_key/lights/$light/state     
}

set_xy () {
    HELPTEXT="
CIE set color xy {x} {y} {brightness:1-254}

"

    maybe_help_needed "$@"
    if [ "$3" = "" ] ; then
        show_help 1 too few parameters specified
    else
	case $3 in
	    max) BRIGHTNESS=254 ;;
	    min) BRIGHTNESS=1 ;;
	    *)  BRIGHTNESS=$3 ;;
	esac
    fi    
    mandatory_lights
    
    feedback setting CIE color of light $light to "$@" 
    polite_curl -s -X PUT -d '{"on":true, "xy":['$1', '$2'], "bri":'$BRIGHTNESS'}' http://$bridge_ip/api/$user_key/lights/$light/state 
}

set_ct () {
    HELPTEXT="
hue set color ct  {mirek:153-500} {brightness:1-254}
            153 - cold -- 500 - warm
"
    maybe_help_needed "$@"    
    if [ "$2" = "" ] ; then
        show_help 1 too few parameters specified
    else
	case $2 in
	    max) BRIGHTNESS=254 ;;
	    min) BRIGHTNESS=1 ;;
	    *)  BRIGHTNESS=$2 ;;
	esac
    fi    
    mandatory_lights
    feedback setting light $light to  mirek "$@"
    polite_curl -s -X PUT -d '{"on":true, "ct":'$1', "bri":'$BRIGHTNESS'}' http://$bridge_ip/api/$user_key/lights/$light/state 
}
    
set_color () { 
    HELPTEXT="
hue set color 
          hue {hue:0-65000} {saturation:1-254} {brightness:1-254}
          xy  {x} {y} {brightness:1-254}
          ct  {mirek:153-500} {brightness:1-254}
            or named color:       
          red|orange|yellow|green|blue|violet
            or temperature 
          T1000 - T20000 -- color temperature in K
"
    maybe_help_needed "$@"
    mandatory_lights
    case $1 in 
        help)
            show_help 0
            ;;
        *)
            mandatory_lights
            set_bulb_color $light "$@"
            ;;        
    esac
}

describe_color () { # returns xy values for named color
    case $1 in
        red)
            COLOR=$RED_COLOR
            ;;
        orange)
            COLOR=$ORANGE_COLOR
            ;;
        yellow)
            COLOR=$YELLOW_COLOR
            ;;
        green)
            COLOR=$GREEN_COLOR
            ;;
        blue)
            COLOR=$BLUE_COLOR
            ;;
        violet)
            COLOR=$VIOLET_COLOR
            ;;
        T*)            
            COLOR=$( K_2_xy $1 )
            ;;
        *)
            show_help 1 Unknown schema/color $* 
            ;;
    esac    
    echo $COLOR
}

set_bulb_color () { # this is Internal procedure not accessible 
    light=$1
    shift
    schema=$1
    shift
    case $schema in
	xy)	
            set_xy "$@"
            FAKE_xy="xy $*"
            ;;
        ct)
            set_ct "$@"
            FAKE_ct="ct $*"
            ;;
        hue)
            set_hue "$@"
            FAKE_hue="hue $*"
            ;;
	[tT])
            if [ "$2" = "" ] ; then
                show_help 1 temperature and brightness expected
            fi
	    COLOR=$( K_2_xy T$1 )
	    FAKE_t="T $1"
	    set_xy $COLOR $2 T$1
	    ;;
        *)
            COLOR=$( describe_color $schema )
            FAKE_xy="xy $COLOR $1"
            if [ "$1" = "" ] ; then
                show_help 1 no brightness 
            fi
            set_xy $COLOR $*
            ;;
    esac
    
}


set_saturation () { 
    HELPTEXT="
hue set saturation {saturation:1-254} - setting saturation
"
    maybe_help_needed "$@"    
    if [ "$1" = "" ] ; then
        show_help 1 no saturation value
    fi    
    mandatory_lights
    feedback setting saturation to "$@" 
    for light ; do
        polite_curl -s -X PUT -d '{"sat":'$v'}' http://$bridge_ip/api/$user_key/lights/$light/state 
    done
}


show_sequence () { 
    #TODO: help
    HELPTEXT="
feed STDIN with color data
"
    maybe_help_needed "$@"
    if [ "$1" = "help" ] ; then
        show_help 0
    fi
    mandatory_lights
    while read one two three four ; do 
        case one in
            xy|hue) 
                feedback setting $one $two $three $four
                set_color $one $two $three $four
                ;;
            ct) 
                feedback setting ct $two $three
                set_color ct $two $three
                ;;
            *) 
                feedback setting xy $one $two $three
                set_color xy $one $two $three
                ;;
        esac           
        sleep $SLEEP
        maybe_give_up $light
    done 
}


sunrise () { 
    #TODO: help, internal interpolation
    maybe_help_needed "$@"
    mandatory_lights
    if [ "$EXP" = "1" ] ; then
	echo -e "$SUNRISE" |$(dirname $0)/../scripts/interpolate.pl $STEPS %f %f *%d  | show_sequence
    else
	echo -e "$LINEAR_SUNRISE" |$(dirname $0)/../scripts/interpolate.pl $STEPS %f %f %d  | show_sequence
    fi
}


sunset () { 
    #TODO: help, internal interpolation
    maybe_help_needed "$@"
    mandatory_lights
    if [ "$EXP" = "1" ] ; then
	echo -e "$SUNRISE" |tac|$(dirname $0)/../scripts/interpolate.pl $STEPS %f %f *%d  | show_sequence
    else
	echo -e "$LINEAR_SUNRISE" |tac|$(dirname $0)/../scripts/interpolate.pl $STEPS %f %f %d  | show_sequence
    fi
    set_light off 
}

set_value() {
    HELPTEXT="
hue set 
       brightness value - set brightness (1-254)
       saturation value - set saturation (1-254)
       color 
         hue {hue} {saturation} {brightness}
         xy  {x} {y} {brightness}
         ct  {mirek} {brightness}
      light
         on
         off
"
    mandatory_lights
    cmd=$1
    shift
    case $cmd in
        brightness)
            set_brightness "$@"
            ;;
        saturation)
            set_saturation "$@"
            ;;
        color)            
            set_color "$@"
            ;;
        light)
            set_light "$@"
            ;;
        *)
            show_help 1 unknown parameter
            ;;
    esac
}

get_value() {
    HELPTEXT="
hue get
        brightness - brightness of light
        onoff  - on/off status of light
        config - full bridge config JSON
        color  - get color description 
        lights - lights data in JSON format
        mode   - current color mode (hue/xy/ct)
"
    maybe_help_needed "$@"
    cmd=$1
    shift
    case $cmd in
        brightness)
	    get_brightness "$@"
            ;;
        onoff)
            get_on_off "$@"
	    ;;
        config)
            feedback getting config
	    get_config_json "$@"
            ;;
        lights)
	    get_lights_json "$@"
	    ;;
        color)
	    get_color $1
            ;;
        mode)
            ;;
        *)
            show_help 1 unknown query: $*
            ;;
    esac
}


HELPTEXT="
Usage: 
  hue [-b bridge_ip][-d[schema]][-e][-h][-k user_key][[-l number] ... ][-o][-p period][-r][-s steps][[-v[level]] ... ] command
    Options are:
      -b|--bridge_ip   -- IP address of the hue bridge device
      -d|--dry[schema] -- dry run, do not bother the bridge (fake response with schema)
      -e|--exp         -- exponential brightness changes in sequencess or transitions
      -h|--help        -- this help
      -k|--key         -- user key for the bridge
      -l|--light       -- light to change (add -l for every light or list in quoted string)
                          --light is MANDATORY for some commands
      -o|--off         -- turn the light off in the end of action
      -p|--period      -- period for blinks in seconds (default ${SLEEP}s)
      -P|--persist     -- keep changing lights even when they were turned off
      -r|--responses   -- show http responses from the bridge
      -s|--steps       -- number of steps in transitions
      -v|--verbose     -- give feedback on taken actions (more -v increases level)
    Commands are:
      alert - one blink please
      blink 
        until - start blinking until date/time
        for   - start blinking for some time
        once  - just blink once
        times - blink number of times
      chase   - make lights chase each other colors #TODO
      clone LIGHT - set light as another light 
      crawl   - make random changes in colors #TODO
      fade 
        until - fade away until date/time #TODO
        for   - fade away for some time #TODO
      get 
        config - fetch config from bridge in JSON
        lights - get lights status in JSON
        brightness LIGHT - get light brightness value for LIGHT
        onoff LIGHT - get on/of status of the light LIGHT
        color LIGHT - get color description of the light LIGHT
      is
        on - return \"light is on\" status (0/1 - true/false) 
      loop #TODO
        mode  - start color loop mode #TODO
        custom  - start custom color loop #TODO
      on           - turn on the light
      off          - turn off the light
      pulse COLOR  - set COLOR for a period and go back
      scan         - scan network for a bridge
      set 
        color COLOR - set all color parameters
        brightness  - set brightness 
        saturation  - set saturation
        light 
          on       - turn on the light
          off      - turn off the light
      show    - show sequence 
      sunset  - show sunset sequence 
      sunrise - show sunrise sequence 
      transit      - gently transit to new color 
      transit from - gently transit to new color from given color

LIGHT - number of light source
COLOR - color description: run 
  $(basename $0) color help
for help on describing color
"

mandatory_lights () {
    if [ "$LIGHTS" = "" ] ; then
        echo "Unknown command or mandatory lights not specified. Try $0 -h"
        exit 1
    fi
}

show_help () {
    if [ "$1" = "0" ] ; then
        echo "$HELPTEXT" 
        exit 0
    else
        if [ "$2" != "" ] ; then
            shift
	    echo error: $* >&2  #TODO: if debug            
        fi
        if [ "$VERBOSE" = "1" ] ; then
            echo "$HELPTEXT" >&2
        fi
        exit 1
    fi
}

while true ; do
    case "$1" in
        -b|--bridge)
            bridge_ip="$2"; shift 2;;
        -d|--dry)
            DRY=1; 
            if [ "$2" != "" ] ; then
                DRY_SCHEMA=$2 # for fake response 
            fi
            shift 2;
            ;;
	-e|--exp)
	    EXP="1"; shift ;;
        -h|--help)
            show_help 0 ;;
        -k|--key)
            user_key="$2"; shift 2;;
        -l|--light)
            LIGHTS="$LIGHTS $2"; shift 2;;
	-o|--off)
	    OFF=1; shift ;;
	-p|--period)
	    SLEEP="$2"; shift 2;;
        -P|--persist)
            PERSIST=1 ; shift ;;
        -r|--responses)
            SHOW_RESPONSES=1;  shift ;;
        -s|--steps)
            STEPS="$2"; shift 2 ;;
        -v|--verbose)
            case "$2" in
                "")
                    VERBOSE=$(( $VERBOSE + 1 ));;
                [0-9])
                    VERBOSE="$2" ;;
            esac
            shift 2;;
        --) 
            shift ; break ;;
        *) echo "Internal error!" ; exit 1 ;;
    esac
done

cmd=$1
shift
if [ "$cmd" = "" ] ; then
    echo "No command specified. Try $0 -h "
    exit 1
fi

debug param: "$@" # DEBUG

case $cmd in
    alert)
        for_lights alert "$@"
	;;
    blink)
        for_lights blink "$@" 
	;;
    color)
        for_lights set_color "$@" 
	;;
    chase)  ## TODO: help support needed!
        for_lights chase $LIGHTS $LIGHTS "$@"
        ;;
    crawl) ## TODO: help support needed!
	for_lights crawl "$@"
	;;
    help)
        show_help 0
        ;;
    scan)
	discover_bridge
	exit 0
	;;
    get)
	get_value "$@"
	;;
    is)
	is_light_on "$@"
	;;
    dump)
	dump_data
	exit 0
	;;
    pulse)
        for_lights hue_pulse "$@" 
	;;
    set)	
	for_lights set_value "$@"
	;;
    show)
        for_lights show_sequence "$@" 
	;;
    transit)
        for_lights transit_to_color "$@" 
        ;;            
    *)
	mandatory_lights
	case $cmd in
	    clone)                
                for_lights clone_light "$@"
		;;
	    fade)
                for_lights fade "$@" 
		;;
	    loop)
		;;
	    my_loop)
		;;
	    off)
                for_lights set_light off "$@" 
		;;
	    on)
		for_lights set_light on "$@" 
		;;
	    sunrise)
                for_lights $cmd "$@"
		;;
	    sunset)
                for_lights $cmd "$@"
		;;
	    *)
		show_help 1 Unknown command $*
		;;
	esac
	
esac
